[package]
name = "ex07"
version = "0.1.0"
edition = "2021"
default-run = "compare"

[[bin]]
name = "compare"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ftkit = "0.1.0"
